[book]
authors = ["ysykzheng"]
language = "en"
multilingual = false
src = "src"
title = "Artificial Intelligence and Industrial IoT: Investigating the Applications and Impacts of Intelligent Technologies in Industry 4.0"
